### ISSUE TITLE
Error in `validate_labelled()`:

### ISSUE THREAD

**Issue by mgb19** [jacobkap/asciiSetupReader#11]
I am trying to read the NIBRS extract file from ICPSR. However, when I run the code I get the following error:

 Error in `validate_labelled()`:                                                                                                
! `labels` must be unique.

My code looks like this:

data11_1 = ("xaa.txt")
setup_file11 = ("34603-0004-Setup.sps")
dt11_1 = read_ascii_setup(data = data11_1, setup_file = setup_file11)

I am using the National Incident-Based Reporting System, 2011: Extract Files (ICPSR 34603) (DS0004) from ICPSR. The code was working perfectly before. I am not sure what the issue is. I had to split the large file into multiple txt files to help speed the process.

**Comment by jacobkap** [comment]
Please submit a minimal reproducible example (https://stackoverflow.com/help/minimal-reproducible-example). But first, retry it without splitting the file into multiple txt files.

**Comment by mgb19** [comment]
I tried running it without splitting the file, but the program keeps running and never returns the output because the sizes of the files are larger than 5GB. Do you have any suggestions? Thank you in advance.

**Comment by jacobkap** [comment]
What code did you use to split the file?

**Comment by mgb19** [comment]
I split them using mac terminal. 

split -b 500m  data.txt

**Comment by jacobkap** [comment]
Since you didn't do it in R I'll need to see the file. Can you upload it?

**Comment by mgb19** [comment]
The file is way too big to upload it. I will try to run the asciiSetupReader using the original file again. I will let you know if the problem persists. 

Thank you for you time and help!

**Comment by mgb19** [comment]
I was able to read all the files using your asciiSetupReader. I believe the problem I was experiencing was because I split the files using the computer's command line.
