### ISSUE TITLE
read_ascii_setup function no longer a part of the package

### ISSUE THREAD

**Issue by aaronkirkman** [jacobkap/asciiSetupReader#2]
It looks like the read_ascii_setup function is no longer a part of the package, but the README.Rmd does not reflect this. This code returns an error that the function could not be found:

```
install.packages("asciiSetupReader")
library(asciiSetupReader)
read_ascii_setup()
```

**Comment by jacobkap** [comment]
Can you try 
devtools::install_github("jacobkap/asciiSetupReader")
library(asciiSetupReader)
read_ascii_setup()

read_ascii_setup() isn't on the CRAN version of the package yet.

**Comment by aaronkirkman** [comment]
It throws the same error, even after installing it from Github.

**Comment by jacobkap** [comment]
Thanks for letting me know. I'll look into it this weekend.

Best,
Jacob

**Comment by jacobkap** [comment]
I'm not able to reproduce this bug. All tests are successful on Appveyor and TravisCI. Can you send me the output from `session_info()` 

and the output from:
devtools::install_github("jacobkap/asciiSetupReader")
library(asciiSetupReader)
read_ascii_setup

**Comment by aaronkirkman** [comment]
In a clean R session, that code works. Huh. I must have kept the CRAN version loaded somehow; that's an error on my end. Thanks!
