### ISSUE TITLE
Failure with dev haven

### ISSUE THREAD

**Issue by hadley** [jacobkap/asciiSetupReader#3]
I see the following errors which all have the same root cause: haven now checks that labels are unique, and you're producing non-unique labels. Can you please take a look and see if you can get a fix to CRAN soon?

*   checking examples ... ERROR
    ```
    ...
    +   package = "asciiSetupReader")
    > 
    > ## Not run: 
    > ##D example <- read_ascii_setup(data = dataset_name,
    > ##D   setup_file = sps_name)
    > ##D 
    > ##D 
    > ##D # Does not fix value labels
    > ##D example2 <- read_ascii_setup(data = dataset_name,
    > ##D   setup_file = sps_name, use_value_labels = FALSE)
    > ##D 
    > ##D # Keeps original column names
    > ##D example3 <- read_ascii_setup(data = dataset_name,
    > ##D   setup_file = sps_name, use_clean_names = FALSE)
    > ## End(Not run)
    > 
    > # Only returns the first 5 columns
    > example4 <- read_ascii_setup(data = dataset_name,
    +   setup_file = sps_name, select_columns = 1:5)
    Error: `labels` must be unique
    Execution halted
    ```

*   checking tests ...
    ```
     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Complete output:
      > library(testthat)
      > library(asciiSetupReader)
      > 
      > test_check("asciiSetupReader")
      Error: `labels` must be unique
      Execution halted
    ```

*   checking re-building of vignette outputs ... WARNING
    ```
    Error in re-building vignettes:
      ...
    Quitting from lines 20-28 (Introduction_to_asciiSetupReader.Rmd) 
    Error: processing vignette 'Introduction_to_asciiSetupReader.Rmd' failed with diagnostics:
    `labels` must be unique
    Execution halted
    ```

**Comment by jacobkap** [comment]
Thanks Hadley. Yes, I'll look into it tonight and try to get a fix to CRAN very soon.

**Comment by jacobkap** [comment]
Okay, I downloaded the dev version of Haven and fixed the bug. All tests are passing on my local machine, not sure how to check TravisCI and AppVeyor using the dev version of Haven. Can you check the dev version of this package and let me know if it works on your end?

**Comment by hadley** [comment]
I don't have any particularly easy way to check that it works — since the problem is so obvious, if it works for you locally with dev haven, I think you should be good to submit to CRAN.

If you really wanted to test on travis, you could do something like this:

```yaml
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
  - r: release
    env: haven='CRAN'
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: release
    env: haven='github'
    before_script: 
    - Rscript -e "remotes::install_github('tidyverse/haven')"
```

It will run two checks, one with CRAN haven and the other with github haven.

**Comment by jacobkap** [comment]
Submitted to CRAN.

**Comment by sjkiss** [comment]
I'm finding this same problem, running Haven 2.1.1 
Looking at the 14th variable, I think the issue is that the value labels are empty. I am aware there are problems with the underlying data file, but wanted to point this out. 
```

#load libraries
library(tidyverse)
library(haven)
library(labelled)
library(here)
#load data file
on18<-read_sav(file='https://github.com/sjkiss/ON18/raw/master/Data/Opes_v_2.sav')

# This is the first problematic variable
on18 %>% 
  select(14) %>% 
  val_labels()

```

**Comment by jacobkap** [comment]
Hi @sjkiss 

Does this issue relate to the asciiSetupReader package? Your code only uses other packages.

**Comment by sjkiss** [comment]
No, it does not. I missed the link to that.  Is there a place I should file this?

**Comment by jacobkap** [comment]
If the issue is related to the haven package, here is the appropriate link to post. https://github.com/tidyverse/haven/issues
