### ISSUE TITLE
Error: `labels` must be unique

### ISSUE THREAD

**Issue by jon-mellon** [jacobkap/asciiSetupReader#4]
I'm trying to use spss_ascii_reader to read in the 1970-1973 Dutch Parliamentary Election Study (available here https://www.icpsr.umich.edu/icpsrweb/ICPSR/studies/7261/). 

I use the following files from that webpage:
07261-0001-Setup.sps 
07261-0001-Data.txt

and the following syntax:

``
dpes_7073 <- spss_ascii_reader(dataset_name = "07261-0001-Data.txt", 
                               sps_name = "07261-0001-Setup.sps")
``

and I get the following errors:

``
Error: `labels` must be unique
In addition: Warning messages:
1: In matrix(value_label_section, ncol = 2, byrow = TRUE) :
  data length [123] is not a sub-multiple or multiple of the number of rows [62]
2: In matrix(value_label_section, ncol = 2, byrow = TRUE) :
  data length [123] is not a sub-multiple or multiple of the number of rows [62]
3: In matrix(value_label_section, ncol = 2, byrow = TRUE) :
  data length [123] is not a sub-multiple or multiple of the number of rows [62]
``

I was able to read in this dataset in a previous version of either this package or the haven package (which I believe this package relies on). I've updated to the latest github versions of both packages and I'm still getting these errors.

Thanks!

**Comment by jacobkap** [comment]
Hi,

Thanks for sending in the bug report. I'll take a look tonight.

**Comment by jon-mellon** [comment]
Thanks for the quick response and for making the package.

**Comment by jacobkap** [comment]
Sorry this took so long. Can you try it with the new GitHub version of this package?

**Comment by jon-mellon** [comment]
Great that looks like it's fixed now.
