### ISSUE TITLE
Weird error when start column > end column

### ISSUE THREAD

**Issue by aaronrudkin** [jacobkap/asciiSetupReader#6]
Hi. @deholliday and I ran into an unusual error using asciiSetupReader when the SPS file used to contain the column information itself contains an error. if any column has a start value > its end value (e.g. start 2000, end 1980), asciiSetupReader's `read_data` function will read in the data fine, but the `data.table:::as.data.table` line will error, producing the useless error message "Error in copy(x) : R character strings are limited to 2^31-1 bytes", which doesn't really highlight the cause of the error.

The bug is actually downstream in the vroom package (see https://github.com/r-lib/vroom/issues/217) but I think generally it's good for every package in the supply chain to have appropriate error checking and friendly user-facing errors.

The actual data we are working with is private so I can't easily produce a reprex that goes through asciiSetupReader, but I think if you look at the vroom version of the issue you'll see a pretty clear reprex with toy data.

**Comment by jacobkap** [comment]
Hi @aaronrudkin thanks for opening this issue. You're right, there should be a check that the column information is valid. I'll make that check and update the package.
