### ISSUE TITLE
Error in parse_setup() to parse_missing_sps()

### ISSUE THREAD

**Issue by rossellhayes** [jacobkap/asciiSetupReader#7]
`parse_setup()` calls `parse_missing_sps()` if `any(grepl2("MISSING VALUE", codebook))`.
However, `parse_missing_sps()` sets `start <- grep2("MISSING VALUES$", codebook)`.

My codebook has one line that contains `"MISSING VALUE"`: `* SPSS MISSING VALUE RECODE *. `
However, it doesn't contain `"MISSING VALUES$"`. As a result, `parse_missing_sps()` is called but fails because `start` has length 0.

**Comment by jacobkap** [comment]
Hi @rossellhayes , can you please send me your codebook so I can use it for tests?

**Comment by rossellhayes** [comment]
Thank you! I converted the codebook to a .txt in order to attach it, but the original file type is .sps.

[09553-0001-Setup.txt](https://github.com/jacobkap/asciiSetupReader/files/4351746/09553-0001-Setup.txt)
