### ISSUE TITLE
Grep error

### ISSUE THREAD

**Issue by thomas-yuen** [jacobkap/asciiSetupReader#8]
Hi, I noticed that the grep error was discussed and issue had been closed. I am facing a similar problem now - I have an .asc file and an SPSS setup file, and I hope to output it into something I can analyse using R.

```r
library(asciiSetupReader)
library(readr)
d <- read_file("CA_SEDD_2005_AHAL_trimmed.asc")
s <- read_file("CA_SEDD_2005_AHAL.sps")
output <- read_ascii_setup(data = d, setup_file = s)
```

However, when I run the program, the error says 'Error in grep2("^INPUT$", codebook):second_grep_value : 
  argument of length 0'. Is there anything wrong with my codes? Thanks!

**Comment by jacobkap** [comment]
Fixed in dev version of this package.
