### ISSUE TITLE
Error in grep2

### ISSUE THREAD

**Issue by sophiecetre** [jacobkap/asciiSetupReader#9]
Hi! Thanks a lot for developing this package, this is exactly what I have been looking for!

I am trying to import a French survey on risk perceptions available here: https://barometre.irsn.fr/graphiques/
I have downloaded one wave for an example (two files: .dat and .sps) that you can find here: https://github.com/sophiecetre/Survey_ascii 

I get the same error that others have already pointed, although the fixes you did don't seem to work for me.

My code is the following:

```
df <- asciiSetupReader::read_ascii_setup(data ="Barometre-55.dat",
                                             setup_file = "Barometre-55.sps")
```

And I get the following error:
```
Error in grep2("DATA LIST|/VARIABLES =$", codebook):second_grep_value : 
  argument of length 0
```

Thanks a lot!
Sophie

**Comment by jacobkap** [comment]
Hi, the issue seems to be that section headers of this setup file differ from ones from the US. So the grep doesn't work given the differences. Unfortunately I don't have time to support languages other than English.
